<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en" class="no-js ie6 lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" class="no-js ie7 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" class="no-js ie8 lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if gt IE 9]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
  
  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- Document Title -->
  <title>Chat app</title>
  <meta name="description" content="Chat app">
  <meta name="application-name" content="Chat app">
  <meta name="author" content="Martin Homola">
  <meta name="robots" content="noindex, nofollow">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" media="screen" href="styles/build/styles.css">
  <link rel="stylesheet" media="print" href="styles/build/print.css">

  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
    <div id="signup" class="signup"></div>
    
  	<!-- Scripts
  	–––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="app/frontend/plugins.js"></script>
    <script src="app/frontend/signup.js"></script>
</body>
</html>
